name: CI/CD for Simple HTML with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t tripfindy/portfolio-app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push tripfindy/portfolio-app:latest

      - name: Test Docker image
        run: |
          docker run -d --name portfolio-app-test -p 80:80 tripfindy/portfolio-app:latest
          sleep 10 # Give the container some time to start
          docker ps | grep portfolio-app-test
          if [ $? -eq 0 ]; then
            echo "Docker image tested successfully"
            docker stop portfolio-app-test
          else
            echo "Docker image test failed"
            exit 1
          fi
          docker rm portfolio-app-test

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Update this to the directory containing your HTML files
