name: CI/CD for Simple HTML with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t icortex-co/portfolio-app:latest .

      - name: Tag Docker image
        run: docker tag icortex-co/portfolio-app:latest icortex-co/portfolio-app:latest

      - name: Push Docker image to Docker Hub
        run: docker push icortex-co/portfolio-app:latest

      - name: Test Docker image
        run: |
          docker run --rm icortex-co/portfolio-app:latest
          echo "Docker image tested successfully"

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
