name: CI/CD for Simple HTML with Docker

on:
  push:
    branches:
      - main
      - portfolio
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
    

      - name: Build Docker image
        run: docker build -t portfolio-app .

      - name: Test Docker image (optional)
        run: |
          # Add testing commands if needed
          echo "No tests for Docker image"

      # - name: Deploy Docker image to DockerHub (optional)
      #   run: |
      #     docker tag portfolio-app ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest
      #     docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest

      - name: Check if on main branch
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "Deployment triggered from main branch"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
